# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

# Build documentation in the docs/ directory with Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements to install
python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
