import 'models/ingredient.dart';
import 'models/recipe.dart';
import 'models/store.dart';

const _storeAldi = 's-aldi';
const _storeWaitrose = 's-waitrose';
const _storeTesco = 's-tesco';
const _storeAsda = 's-asda';

Ingredient _i(
  String name,
  double cost,
  double distance,
  int calories, {
  String? genericName,
  String? storeId,
}) => Ingredient(
  name: name,
  genericName: genericName,
  cost: cost,
  distance: distance,
  calories: calories,
  storeId: storeId,
);

final Map<String, List<Ingredient>> marketInventory = {
  'Flour': [
    _i('Flour (Aldi)', 0.70, 3.0, 360, genericName: 'Flour', storeId: _storeAldi),
    _i('Flour (Waitrose)', 0.85, 1.0, 3640, genericName: 'Flour', storeId: _storeWaitrose),
    _i('Flour (Tesco)', 0.80, 2.5, 3640, genericName: 'Flour', storeId: _storeTesco),
    _i('Flour (Asda)', 0.78, 1.5, 3640, genericName: 'Flour', storeId: _storeAsda),
  ],
  'Milk': [
    _i('Milk (Aldi)', 1.55, 3.0, 1000, genericName: 'Milk', storeId: _storeAldi),
    _i('Milk (Waitrose)', 2.20, 1.0, 1000, genericName: 'Milk', storeId: _storeWaitrose),
    _i('Milk (Tesco)', 1.80, 2.5, 1000, genericName: 'Milk', storeId: _storeTesco),
    _i('Milk (Asda)', 1.65, 1.5, 1000, genericName: 'Milk', storeId: _storeAsda),
  ],
  'Eggs': [
    _i('Eggs (Aldi)', 2.20, 3.0, 1115, genericName: 'Eggs', storeId: _storeAldi),
    _i('Eggs (Waitrose)', 3.50, 1.0, 1115, genericName: 'Eggs', storeId: _storeWaitrose),
    _i('Eggs (Tesco)', 2.80, 2.5, 1115, genericName: 'Eggs', storeId: _storeTesco),
    _i('Eggs (Asda)', 2.50, 1.5, 1115, genericName: 'Eggs', storeId: _storeAsda),
  ],
  'Lettuce': [
    _i('Lettuce (Aldi)', 3.00, 3.0, 150, genericName: 'Lettuce', storeId: _storeAldi),
    _i('Lettuce (Waitrose)', 4.50, 1.0, 150, genericName: 'Lettuce', storeId: _storeWaitrose),
    _i('Lettuce (Tesco)', 3.80, 2.5, 150, genericName: 'Lettuce', storeId: _storeTesco),
    _i('Lettuce (Asda)', 3.20, 1.5, 150, genericName: 'Lettuce', storeId: _storeAsda),
  ],
  'Tomatoes': [
    _i('Tomatoes (Aldi)', 2.00, 3.0, 180, genericName: 'Tomatoes', storeId: _storeAldi),
    _i('Tomatoes (Waitrose)', 3.00, 1.0, 180, genericName: 'Tomatoes', storeId: _storeWaitrose),
    _i('Tomatoes (Tesco)', 2.50, 2.5, 180, genericName: 'Tomatoes', storeId: _storeTesco),
    _i('Tomatoes (Asda)', 2.20, 1.5, 180, genericName: 'Tomatoes', storeId: _storeAsda),
  ],
  'Cucumber': [
    _i('Cucumber (Aldi)', 2.00, 3.0, 160, genericName: 'Cucumber', storeId: _storeAldi),
    _i('Cucumber (Waitrose)', 3.00, 1.0, 160, genericName: 'Cucumber', storeId: _storeWaitrose),
    _i('Cucumber (Tesco)', 2.50, 2.5, 160, genericName: 'Cucumber', storeId: _storeTesco),
    _i('Cucumber (Asda)', 2.20, 1.5, 160, genericName: 'Cucumber', storeId: _storeAsda),
  ],
  'Pasta': [
    _i('Pasta (Aldi)', 0.75, 3.0, 1580, genericName: 'Pasta', storeId: _storeAldi),
    _i('Pasta (Waitrose)', 1.50, 1.0, 1580, genericName: 'Pasta', storeId: _storeWaitrose),
    _i('Pasta (Tesco)', 1.19, 2.5, 1580, genericName: 'Pasta', storeId: _storeTesco),
    _i('Pasta (Asda)', 1.29, 1.5, 1580, genericName: 'Pasta', storeId: _storeAsda),
  ],
  'Salt': [
    _i('Salt (Aldi)', 0.65, 3.0, 0, genericName: 'Salt', storeId: _storeAldi),
    _i('Salt (Waitrose)', 0.75, 1.0, 0, genericName: 'Salt', storeId: _storeWaitrose),
    _i('Salt (Tesco)', 1.90, 2.5, 0, genericName: 'Salt', storeId: _storeTesco),
    _i('Salt (Asda)', 0.70, 1.5, 0, genericName: 'Salt', storeId: _storeAsda),
  ],
  'Pepper': [
    _i('Pepper (Aldi)', 1.59, 3.0, 250, genericName: 'Pepper', storeId: _storeAldi),
    _i('Pepper (Waitrose)', 2.80, 1.0, 250, genericName: 'Pepper', storeId: _storeWaitrose),
    _i('Pepper (Tesco)', 2.55, 2.5, 250, genericName: 'Pepper', storeId: _storeTesco),
    _i('Pepper (Asda)', 2.20, 1.5, 250, genericName: 'Pepper', storeId: _storeAsda),
  ],
  'Sugar': [
    _i('Sugar (Aldi)', 1.09, 3.0, 3870, genericName: 'Sugar', storeId: _storeAldi),
    _i('Sugar (Waitrose)', 1.25, 1.0, 3870, genericName: 'Sugar', storeId: _storeWaitrose),
    _i('Sugar (Tesco)', 1.09, 2.5, 3870, genericName: 'Sugar', storeId: _storeTesco),
    _i('Sugar (Asda)', 1.09, 1.5, 3870, genericName: 'Sugar', storeId: _storeAsda),
  ],
  'Rice': [
    _i('Rice (Aldi)', 0.52, 3.0, 3600, genericName: 'Rice', storeId: _storeAldi),
    _i('Rice (Waitrose)', 1.60, 1.0, 3600, genericName: 'Rice', storeId: _storeWaitrose),
    _i('Rice (Tesco)', 1.25, 2.5, 3600, genericName: 'Rice', storeId: _storeTesco),
    _i('Rice (Asda)', 1.25, 1.5, 3600, genericName: 'Rice', storeId: _storeAsda),
  ],
  'Oats': [
    _i('Oats (Aldi)', 0.75, 3.0, 3700, genericName: 'Oats', storeId: _storeAldi),
    _i('Oats (Waitrose)', 1.25, 1.0, 3700, genericName: 'Oats', storeId: _storeWaitrose),
    _i('Oats (Tesco)', 1.35, 2.5, 3700, genericName: 'Oats', storeId: _storeTesco),
    _i('Oats (Asda)', 0.85, 1.5, 3700, genericName: 'Oats', storeId: _storeAsda),
  ],
  'Baking Powder': [
    _i('Baking Powder (Aldi)', 0.79, 3.0, 53, genericName: 'Baking Powder', storeId: _storeAldi),
    _i('Baking Powder (Waitrose)', 1.20, 1.0, 53, genericName: 'Baking Powder', storeId: _storeWaitrose),
    _i('Baking Powder (Tesco)', 0.85, 2.5, 53, genericName: 'Baking Powder', storeId: _storeTesco),
    _i('Baking Powder (Asda)', 0.70, 1.5, 53, genericName: 'Baking Powder', storeId: _storeAsda),
  ],
  'Olive Oil': [
    _i('Olive Oil (Aldi)', 4.49, 3.0, 8840, genericName: 'Olive Oil', storeId: _storeAldi),
    _i('Olive Oil (Waitrose)', 6.50, 1.0, 8840, genericName: 'Olive Oil', storeId: _storeWaitrose),
    _i('Olive Oil (Tesco)', 5.25, 2.5, 8840, genericName: 'Olive Oil', storeId: _storeTesco),
    _i('Olive Oil (Asda)', 5.00, 1.5, 8840, genericName: 'Olive Oil', storeId: _storeAsda),
  ],
  'Vegetable Oil': [
    _i('Vegetable Oil (Aldi)', 2.25, 3.0, 8840, genericName: 'Vegetable Oil', storeId: _storeAldi),
    _i('Vegetable Oil (Waitrose)', 3.50, 1.0, 8840, genericName: 'Vegetable Oil', storeId: _storeWaitrose),
    _i('Vegetable Oil (Tesco)', 2.60, 2.5, 8840, genericName: 'Vegetable Oil', storeId: _storeTesco),
    _i('Vegetable Oil (Asda)', 2.50, 1.5, 8840, genericName: 'Vegetable Oil', storeId: _storeAsda),
  ],
  'Butter': [
    _i('Butter (Aldi)', 1.99, 3.0, 1790, genericName: 'Butter', storeId: _storeAldi),
    _i('Butter (Waitrose)', 2.30, 1.0, 1790, genericName: 'Butter', storeId: _storeWaitrose),
    _i('Butter (Tesco)', 2.10, 2.5, 1790, genericName: 'Butter', storeId: _storeTesco),
    _i('Butter (Asda)', 2.00, 1.5, 1790, genericName: 'Butter', storeId: _storeAsda),
  ],
  'Mayonnaise': [
    _i('Mayonnaise (Aldi)', 1.29, 3.0, 3400, genericName: 'Mayonnaise', storeId: _storeAldi),
    _i('Mayonnaise (Waitrose)', 2.50, 1.0, 3400, genericName: 'Mayonnaise', storeId: _storeWaitrose),
    _i('Mayonnaise (Tesco)', 2.00, 2.5, 3400, genericName: 'Mayonnaise', storeId: _storeTesco),
    _i('Mayonnaise (Asda)', 1.80, 1.5, 3400, genericName: 'Mayonnaise', storeId: _storeAsda),
  ],
  'Mustard': [
    _i('Mustard (Aldi)', 0.69, 3.0, 120, genericName: 'Mustard', storeId: _storeAldi),
    _i('Mustard (Waitrose)', 1.20, 1.0, 120, genericName: 'Mustard', storeId: _storeWaitrose),
    _i('Mustard (Tesco)', 0.85, 2.5, 120, genericName: 'Mustard', storeId: _storeTesco),
    _i('Mustard (Asda)', 0.75, 1.5, 120, genericName: 'Mustard', storeId: _storeAsda),
  ],
  'Soy Sauce': [
    _i('Soy Sauce (Aldi)', 0.99, 3.0, 80, genericName: 'Soy Sauce', storeId: _storeAldi),
    _i('Soy Sauce (Waitrose)', 1.80, 1.0, 80, genericName: 'Soy Sauce', storeId: _storeWaitrose),
    _i('Soy Sauce (Tesco)', 1.50, 2.5, 80, genericName: 'Soy Sauce', storeId: _storeTesco),
    _i('Soy Sauce (Asda)', 1.30, 1.5, 80, genericName: 'Soy Sauce', storeId: _storeAsda),
  ],
  'Vinegar': [
    _i('Vinegar (Aldi)', 0.35, 3.0, 90, genericName: 'Vinegar', storeId: _storeAldi),
    _i('Vinegar (Waitrose)', 0.90, 1.0, 90, genericName: 'Vinegar', storeId: _storeWaitrose),
    _i('Vinegar (Tesco)', 0.75, 2.5, 90, genericName: 'Vinegar', storeId: _storeTesco),
    _i('Vinegar (Asda)', 0.60, 1.5, 90, genericName: 'Vinegar', storeId: _storeAsda),
  ],
  'Honey': [
    _i('Honey (Aldi)', 1.69, 3.0, 1030, genericName: 'Honey', storeId: _storeAldi),
    _i('Honey (Waitrose)', 3.00, 1.0, 1030, genericName: 'Honey', storeId: _storeWaitrose),
    _i('Honey (Tesco)', 2.50, 2.5, 1030, genericName: 'Honey', storeId: _storeTesco),
    _i('Honey (Asda)', 2.20, 1.5, 1030, genericName: 'Honey', storeId: _storeAsda),
  ],
  'Syrup': [
    _i('Syrup (Aldi)', 1.29, 3.0, 1400, genericName: 'Syrup', storeId: _storeAldi),
    _i('Syrup (Waitrose)', 2.20, 1.0, 1400, genericName: 'Syrup', storeId: _storeWaitrose),
    _i('Syrup (Tesco)', 1.80, 2.5, 1400, genericName: 'Syrup', storeId: _storeTesco),
    _i('Syrup (Asda)', 1.60, 1.5, 1400, genericName: 'Syrup', storeId: _storeAsda),
  ],
  'Onion': [
    _i('Onion (Aldi)', 0.95, 3.0, 400, genericName: 'Onion', storeId: _storeAldi),
    _i('Onion (Waitrose)', 1.50, 1.0, 400, genericName: 'Onion', storeId: _storeWaitrose),
    _i('Onion (Tesco)', 1.20, 2.5, 400, genericName: 'Onion', storeId: _storeTesco),
    _i('Onion (Asda)', 1.00, 1.5, 400, genericName: 'Onion', storeId: _storeAsda),
  ],
  'Garlic': [
    _i('Garlic (Aldi)', 4.00, 3.0, 1490, genericName: 'Garlic', storeId: _storeAldi),
    _i('Garlic (Waitrose)', 6.00, 1.0, 1490, genericName: 'Garlic', storeId: _storeWaitrose),
    _i('Garlic (Tesco)', 5.00, 2.5, 1490, genericName: 'Garlic', storeId: _storeTesco),
    _i('Garlic (Asda)', 4.50, 1.5, 1490, genericName: 'Garlic', storeId: _storeAsda),
  ],
  'Ginger': [
    _i('Ginger (Aldi)', 3.00, 3.0, 800, genericName: 'Ginger', storeId: _storeAldi),
    _i('Ginger (Waitrose)', 5.00, 1.0, 800, genericName: 'Ginger', storeId: _storeWaitrose),
    _i('Ginger (Tesco)', 4.00, 2.5, 800, genericName: 'Ginger', storeId: _storeTesco),
    _i('Ginger (Asda)', 3.50, 1.5, 800, genericName: 'Ginger', storeId: _storeAsda),
  ],
  'Carrots': [
    _i('Carrots (Aldi)', 0.60, 3.0, 410, genericName: 'Carrots', storeId: _storeAldi),
    _i('Carrots (Waitrose)', 1.20, 1.0, 410, genericName: 'Carrots', storeId: _storeWaitrose),
    _i('Carrots (Tesco)', 0.80, 2.5, 410, genericName: 'Carrots', storeId: _storeTesco),
    _i('Carrots (Asda)', 0.70, 1.5, 410, genericName: 'Carrots', storeId: _storeAsda),
  ],
  'Celery': [
    _i('Celery (Aldi)', 1.50, 3.0, 160, genericName: 'Celery', storeId: _storeAldi),
    _i('Celery (Waitrose)', 2.00, 1.0, 160, genericName: 'Celery', storeId: _storeWaitrose),
    _i('Celery (Tesco)', 1.70, 2.5, 160, genericName: 'Celery', storeId: _storeTesco),
    _i('Celery (Asda)', 1.60, 1.5, 160, genericName: 'Celery', storeId: _storeAsda),
  ],
  'Bell Peppers': [
    _i('Bell Peppers (Aldi)', 2.50, 3.0, 310, genericName: 'Bell Peppers', storeId: _storeAldi),
    _i('Bell Peppers (Waitrose)', 3.50, 1.0, 310, genericName: 'Bell Peppers', storeId: _storeWaitrose),
    _i('Bell Peppers (Tesco)', 3.00, 2.5, 310, genericName: 'Bell Peppers', storeId: _storeTesco),
    _i('Bell Peppers (Asda)', 2.80, 1.5, 310, genericName: 'Bell Peppers', storeId: _storeAsda),
  ],
  'Potatoes': [
    _i('Potatoes (Aldi)', 1.20, 3.0, 770, genericName: 'Potatoes', storeId: _storeAldi),
    _i('Potatoes (Waitrose)', 1.80, 1.0, 770, genericName: 'Potatoes', storeId: _storeWaitrose),
    _i('Potatoes (Tesco)', 1.50, 2.5, 770, genericName: 'Potatoes', storeId: _storeTesco),
    _i('Potatoes (Asda)', 1.30, 1.5, 770, genericName: 'Potatoes', storeId: _storeAsda),
  ],
  'Spinach': [
    _i('Spinach (Aldi)', 5.00, 3.0, 230, genericName: 'Spinach', storeId: _storeAldi),
    _i('Spinach (Waitrose)', 7.00, 1.0, 230, genericName: 'Spinach', storeId: _storeWaitrose),
    _i('Spinach (Tesco)', 6.00, 2.5, 230, genericName: 'Spinach', storeId: _storeTesco),
    _i('Spinach (Asda)', 5.50, 1.5, 230, genericName: 'Spinach', storeId: _storeAsda),
  ],
  'Broccoli': [
    _i('Broccoli (Aldi)', 2.00, 3.0, 340, genericName: 'Broccoli', storeId: _storeAldi),
    _i('Broccoli (Waitrose)', 3.00, 1.0, 340, genericName: 'Broccoli', storeId: _storeWaitrose),
    _i('Broccoli (Tesco)', 2.50, 2.5, 340, genericName: 'Broccoli', storeId: _storeTesco),
    _i('Broccoli (Asda)', 2.20, 1.5, 340, genericName: 'Broccoli', storeId: _storeAsda),
  ],
  'Chicken Breast': [
    _i('Chicken Breast (Aldi)', 5.50, 3.0, 1650, genericName: 'Chicken Breast', storeId: _storeAldi),
    _i('Chicken Breast (Waitrose)', 7.50, 1.0, 1650, genericName: 'Chicken Breast', storeId: _storeWaitrose),
    _i('Chicken Breast (Tesco)', 6.50, 2.5, 1650, genericName: 'Chicken Breast', storeId: _storeTesco),
    _i('Chicken Breast (Asda)', 6.00, 1.5, 1650, genericName: 'Chicken Breast', storeId: _storeAsda),
  ],
  'Whole Chicken': [
    _i('Whole Chicken (Aldi)', 4.50, 3.0, 2850, genericName: 'Whole Chicken', storeId: _storeAldi),
    _i('Whole Chicken (Waitrose)', 7.00, 1.0, 2850, genericName: 'Whole Chicken', storeId: _storeWaitrose),
    _i('Whole Chicken (Tesco)', 6.00, 2.5, 2850, genericName: 'Whole Chicken', storeId: _storeTesco),
    _i('Whole Chicken (Asda)', 5.50, 1.5, 2850, genericName: 'Whole Chicken', storeId: _storeAsda),
  ],
  'Minced Beef': [
    _i('Minced Beef (Aldi)', 2.50, 3.0, 1250, genericName: 'Minced Beef', storeId: _storeAldi),
    _i('Minced Beef (Waitrose)', 4.00, 1.0, 1250, genericName: 'Minced Beef', storeId: _storeWaitrose),
    _i('Minced Beef (Tesco)', 3.50, 2.5, 1250, genericName: 'Minced Beef', storeId: _storeTesco),
    _i('Minced Beef (Asda)', 3.00, 1.5, 1250, genericName: 'Minced Beef', storeId: _storeAsda),
  ],
  'Salmon': [
    _i('Salmon (Aldi)', 3.50, 3.0, 520, genericName: 'Salmon', storeId: _storeAldi),
    _i('Salmon (Waitrose)', 5.50, 1.0, 520, genericName: 'Salmon', storeId: _storeWaitrose),
    _i('Salmon (Tesco)', 4.50, 2.5, 520, genericName: 'Salmon', storeId: _storeTesco),
    _i('Salmon (Asda)', 4.00, 1.5, 520, genericName: 'Salmon', storeId: _storeAsda),
  ],
  'Canned Tuna': [
    _i('Canned Tuna (Aldi)', 0.75, 3.0, 170, genericName: 'Canned Tuna', storeId: _storeAldi),
    _i('Canned Tuna (Waitrose)', 1.20, 1.0, 170, genericName: 'Canned Tuna', storeId: _storeWaitrose),
    _i('Canned Tuna (Tesco)', 1.00, 2.5, 170, genericName: 'Canned Tuna', storeId: _storeTesco),
    _i('Canned Tuna (Asda)', 0.90, 1.5, 170, genericName: 'Canned Tuna', storeId: _storeAsda),
  ],
  'Tofu': [
    _i('Tofu (Aldi)', 1.75, 3.0, 300, genericName: 'Tofu', storeId: _storeAldi),
    _i('Tofu (Waitrose)', 2.50, 1.0, 300, genericName: 'Tofu', storeId: _storeWaitrose),
    _i('Tofu (Tesco)', 2.20, 2.5, 300, genericName: 'Tofu', storeId: _storeTesco),
    _i('Tofu (Asda)', 2.00, 1.5, 300, genericName: 'Tofu', storeId: _storeAsda),
  ],
  'Lentils': [
    _i('Lentils (Aldi)', 0.95, 3.0, 1765, genericName: 'Lentils', storeId: _storeAldi),
    _i('Lentils (Waitrose)', 1.80, 1.0, 1765, genericName: 'Lentils', storeId: _storeWaitrose),
    _i('Lentils (Tesco)', 1.40, 2.5, 1765, genericName: 'Lentils', storeId: _storeTesco),
    _i('Lentils (Asda)', 1.10, 1.5, 1765, genericName: 'Lentils', storeId: _storeAsda),
  ],
  'Chickpeas': [
    _i('Chickpeas (Aldi)', 0.55, 3.0, 260, genericName: 'Chickpeas', storeId: _storeAldi),
    _i('Chickpeas (Waitrose)', 0.90, 1.0, 260, genericName: 'Chickpeas', storeId: _storeWaitrose),
    _i('Chickpeas (Tesco)', 0.75, 2.5, 260, genericName: 'Chickpeas', storeId: _storeTesco),
    _i('Chickpeas (Asda)', 0.65, 1.5, 260, genericName: 'Chickpeas', storeId: _storeAsda),
  ],
  'Cheddar Cheese': [
    _i('Cheddar Cheese (Aldi)', 2.50, 3.0, 1608, genericName: 'Cheddar Cheese', storeId: _storeAldi),
    _i('Cheddar Cheese (Waitrose)', 3.50, 1.0, 1608, genericName: 'Cheddar Cheese', storeId: _storeWaitrose),
    _i('Cheddar Cheese (Tesco)', 3.00, 2.5, 1608, genericName: 'Cheddar Cheese', storeId: _storeTesco),
    _i('Cheddar Cheese (Asda)', 2.80, 1.5, 1608, genericName: 'Cheddar Cheese', storeId: _storeAsda),
  ],
  'Parmesan Cheese': [
    _i('Parmesan Cheese (Aldi)', 2.20, 3.0, 862, genericName: 'Parmesan Cheese', storeId: _storeAldi),
    _i('Parmesan Cheese (Waitrose)', 3.50, 1.0, 862, genericName: 'Parmesan Cheese', storeId: _storeWaitrose),
    _i('Parmesan Cheese (Tesco)', 3.00, 2.5, 862, genericName: 'Parmesan Cheese', storeId: _storeTesco),
    _i('Parmesan Cheese (Asda)', 2.70, 1.5, 862, genericName: 'Parmesan Cheese', storeId: _storeAsda),
  ],
  'Plain Yogurt': [
    _i('Plain Yogurt (Aldi)', 0.85, 3.0, 305, genericName: 'Plain Yogurt', storeId: _storeAldi),
    _i('Plain Yogurt (Waitrose)', 1.50, 1.0, 305, genericName: 'Plain Yogurt', storeId: _storeWaitrose),
    _i('Plain Yogurt (Tesco)', 1.20, 2.5, 305, genericName: 'Plain Yogurt', storeId: _storeTesco),
    _i('Plain Yogurt (Asda)', 1.00, 1.5, 305, genericName: 'Plain Yogurt', storeId: _storeAsda),
  ],
  'Greek Yogurt': [
    _i('Greek Yogurt (Aldi)', 1.50, 3.0, 600, genericName: 'Greek Yogurt', storeId: _storeAldi),
    _i('Greek Yogurt (Waitrose)', 2.50, 1.0, 600, genericName: 'Greek Yogurt', storeId: _storeWaitrose),
    _i('Greek Yogurt (Tesco)', 2.00, 2.5, 600, genericName: 'Greek Yogurt', storeId: _storeTesco),
    _i('Greek Yogurt (Asda)', 1.80, 1.5, 600, genericName: 'Greek Yogurt', storeId: _storeAsda),
  ],
  'Double Cream': [
    _i('Double Cream (Aldi)', 1.20, 3.0, 1400, genericName: 'Double Cream', storeId: _storeAldi),
    _i('Double Cream (Waitrose)', 1.80, 1.0, 1400, genericName: 'Double Cream', storeId: _storeWaitrose),
    _i('Double Cream (Tesco)', 1.50, 2.5, 1400, genericName: 'Double Cream', storeId: _storeTesco),
    _i('Double Cream (Asda)', 1.30, 1.5, 1400, genericName: 'Double Cream', storeId: _storeAsda),
  ],
  'Single Cream': [
    _i('Single Cream (Aldi)', 0.95, 3.0, 600, genericName: 'Single Cream', storeId: _storeAldi),
    _i('Single Cream (Waitrose)', 1.40, 1.0, 600, genericName: 'Single Cream', storeId: _storeWaitrose),
    _i('Single Cream (Tesco)', 1.20, 2.5, 600, genericName: 'Single Cream', storeId: _storeTesco),
    _i('Single Cream (Asda)', 1.00, 1.5, 600, genericName: 'Single Cream', storeId: _storeAsda),
  ],
  'Basil': [
    _i('Basil (Aldi)', 0.79, 3.0, 115, genericName: 'Basil', storeId: _storeAldi),
    _i('Basil (Waitrose)', 1.80, 1.0, 115, genericName: 'Basil', storeId: _storeWaitrose),
    _i('Basil (Tesco)', 1.50, 2.5, 115, genericName: 'Basil', storeId: _storeTesco),
    _i('Basil (Asda)', 1.20, 1.5, 115, genericName: 'Basil', storeId: _storeAsda),
  ],
  'Oregano': [
    _i('Oregano (Aldi)', 0.79, 3.0, 130, genericName: 'Oregano', storeId: _storeAldi),
    _i('Oregano (Waitrose)', 1.80, 1.0, 130, genericName: 'Oregano', storeId: _storeWaitrose),
    _i('Oregano (Tesco)', 1.50, 2.5, 130, genericName: 'Oregano', storeId: _storeTesco),
    _i('Oregano (Asda)', 1.20, 1.5, 130, genericName: 'Oregano', storeId: _storeAsda),
  ],
  'Thyme': [
    _i('Thyme (Aldi)', 0.79, 3.0, 140, genericName: 'Thyme', storeId: _storeAldi),
    _i('Thyme (Waitrose)', 1.80, 1.0, 140, genericName: 'Thyme', storeId: _storeWaitrose),
    _i('Thyme (Tesco)', 1.50, 2.5, 140, genericName: 'Thyme', storeId: _storeTesco),
    _i('Thyme (Asda)', 1.20, 1.5, 140, genericName: 'Thyme', storeId: _storeAsda),
  ],
  'Paprika': [
    _i('Paprika (Aldi)', 0.89, 3.0, 140, genericName: 'Paprika', storeId: _storeAldi),
    _i('Paprika (Waitrose)', 2.00, 1.0, 140, genericName: 'Paprika', storeId: _storeWaitrose),
    _i('Paprika (Tesco)', 1.70, 2.5, 140, genericName: 'Paprika', storeId: _storeTesco),
    _i('Paprika (Asda)', 1.40, 1.5, 140, genericName: 'Paprika', storeId: _storeAsda),
  ],
  'Cumin': [
    _i('Cumin (Aldi)', 0.89, 3.0, 190, genericName: 'Cumin', storeId: _storeAldi),
    _i('Cumin (Waitrose)', 2.20, 1.0, 190, genericName: 'Cumin', storeId: _storeWaitrose),
    _i('Cumin (Tesco)', 1.80, 2.5, 190, genericName: 'Cumin', storeId: _storeTesco),
    _i('Cumin (Asda)', 1.50, 1.5, 190, genericName: 'Cumin', storeId: _storeAsda),
  ],
  'Chilli Powder': [
    _i('Chilli Powder (Aldi)', 0.89, 3.0, 140, genericName: 'Chilli Powder', storeId: _storeAldi),
    _i('Chilli Powder (Waitrose)', 2.00, 1.0, 140, genericName: 'Chilli Powder', storeId: _storeWaitrose),
    _i('Chilli Powder (Tesco)', 1.70, 2.5, 140, genericName: 'Chilli Powder', storeId: _storeTesco),
    _i('Chilli Powder (Asda)', 1.40, 1.5, 140, genericName: 'Chilli Powder', storeId: _storeAsda),
  ],
  'Strawberry': [
    _i('Strawberry (Aldi)', 3.00, 3.0, 320, genericName: 'Strawberry', storeId: _storeAldi),
    _i('Strawberry (Waitrose)', 4.50, 1.0, 320, genericName: 'Strawberry', storeId: _storeWaitrose),
    _i('Strawberry (Tesco)', 3.80, 2.5, 320, genericName: 'Strawberry', storeId: _storeTesco),
    _i('Strawberry (Asda)', 3.20, 1.5, 320, genericName: 'Strawberry', storeId: _storeAsda),
  ],
  'Apple': [
    _i('Apple (Aldi)', 2.00, 3.0, 520, genericName: 'Apple', storeId: _storeAldi),
    _i('Apple (Waitrose)', 3.00, 1.0, 520, genericName: 'Apple', storeId: _storeWaitrose),
    _i('Apple (Tesco)', 2.50, 2.5, 520, genericName: 'Apple', storeId: _storeTesco),
    _i('Apple (Asda)', 2.20, 1.5, 520, genericName: 'Apple', storeId: _storeAsda),
  ],
  'Banana': [
    _i('Banana (Aldi)', 1.20, 3.0, 890, genericName: 'Banana', storeId: _storeAldi),
    _i('Banana (Waitrose)', 2.00, 1.0, 890, genericName: 'Banana', storeId: _storeWaitrose),
    _i('Banana (Tesco)', 1.50, 2.5, 890, genericName: 'Banana', storeId: _storeTesco),
    _i('Banana (Asda)', 1.30, 1.5, 890, genericName: 'Banana', storeId: _storeAsda),
  ],
  'Kiwi': [
    _i('Kiwi (Aldi)', 3.00, 3.0, 610, genericName: 'Kiwi', storeId: _storeAldi),
    _i('Kiwi (Waitrose)', 4.50, 1.0, 890, genericName: 'Kiwi', storeId: _storeWaitrose),
    _i('Kiwi (Tesco)', 3.80, 2.5, 610, genericName: 'Kiwi', storeId: _storeTesco),
    _i('Kiwi (Asda)', 3.20, 1.5, 610, genericName: 'Kiwi', storeId: _storeAsda),
  ],
  'Pear': [
    _i('Pear (Aldi)', 2.20, 3.0, 570, genericName: 'Pear', storeId: _storeAldi),
    _i('Pear (Waitrose)', 3.50, 1.0, 570, genericName: 'Pear', storeId: _storeWaitrose),
    _i('Pear (Tesco)', 3.00, 2.5, 570, genericName: 'Pear', storeId: _storeTesco),
    _i('Pear (Asda)', 2.50, 1.5, 570, genericName: 'Pear', storeId: _storeAsda),
  ],
  'Oranges': [
    _i('Oranges (Aldi)', 2.00, 3.0, 470, genericName: 'Oranges', storeId: _storeAldi),
    _i('Oranges (Waitrose)', 3.00, 1.0, 470, genericName: 'Oranges', storeId: _storeWaitrose),
    _i('Oranges (Tesco)', 2.50, 2.5, 470, genericName: 'Oranges', storeId: _storeTesco),
    _i('Oranges (Asda)', 2.20, 1.5, 470, genericName: 'Oranges', storeId: _storeAsda),
  ],
  'Grapes': [
    _i('Grapes (Aldi)', 3.50, 3.0, 690, genericName: 'Grapes', storeId: _storeAldi),
    _i('Grapes (Waitrose)', 5.00, 1.0, 690, genericName: 'Grapes', storeId: _storeWaitrose),
    _i('Grapes (Tesco)', 4.00, 2.5, 690, genericName: 'Grapes', storeId: _storeTesco),
    _i('Grapes (Asda)', 3.80, 1.5, 690, genericName: 'Grapes', storeId: _storeAsda),
  ],
  'Pineapple': [
    _i('Pineapple (Aldi)', 2.00, 3.0, 500, genericName: 'Pineapple', storeId: _storeAldi),
    _i('Pineapple (Waitrose)', 3.50, 1.0, 500, genericName: 'Pineapple', storeId: _storeWaitrose),
    _i('Pineapple (Tesco)', 3.00, 2.5, 500, genericName: 'Pineapple', storeId: _storeTesco),
    _i('Pineapple (Asda)', 2.50, 1.5, 500, genericName: 'Pineapple', storeId: _storeAsda),
  ],
  'Mango': [
    _i('Mango (Aldi)', 2.00, 3.0, 600, genericName: 'Mango', storeId: _storeAldi),
    _i('Mango (Waitrose)', 3.50, 1.0, 600, genericName: 'Mango', storeId: _storeWaitrose),
    _i('Mango (Tesco)', 3.00, 2.5, 600, genericName: 'Mango', storeId: _storeTesco),
    _i('Mango (Asda)', 2.50, 1.5, 600, genericName: 'Mango', storeId: _storeAsda),
  ],
  'Watermelon': [
    _i('Watermelon (Aldi)', 1.50, 3.0, 300, genericName: 'Watermelon', storeId: _storeAldi),
    _i('Watermelon (Waitrose)', 2.50, 1.0, 300, genericName: 'Watermelon', storeId: _storeWaitrose),
    _i('Watermelon (Tesco)', 2.00, 2.5, 300, genericName: 'Watermelon', storeId: _storeTesco),
    _i('Watermelon (Asda)', 1.80, 1.5, 300, genericName: 'Watermelon', storeId: _storeAsda),
  ],
  'Blueberries': [
    _i('Blueberries (Aldi)', 5.00, 3.0, 570, genericName: 'Blueberries', storeId: _storeAldi),
    _i('Blueberries (Waitrose)', 7.00, 1.0, 570, genericName: 'Blueberries', storeId: _storeWaitrose),
    _i('Blueberries (Tesco)', 6.00, 2.5, 570, genericName: 'Blueberries', storeId: _storeTesco),
    _i('Blueberries (Asda)', 5.50, 1.5, 570, genericName: 'Blueberries', storeId: _storeAsda),
  ],
  'Raspberries': [
    _i('Raspberries (Aldi)', 5.00, 3.0, 520, genericName: 'Raspberries', storeId: _storeAldi),
    _i('Raspberries (Waitrose)', 7.50, 1.0, 520, genericName: 'Raspberries', storeId: _storeWaitrose),
    _i('Raspberries (Tesco)', 6.00, 2.5, 570, genericName: 'Raspberries', storeId: _storeTesco),
    _i('Raspberries (Asda)', 5.50, 1.5, 570, genericName: 'Raspberries', storeId: _storeAsda),
  ],
  'Cherries': [
    _i('Cherries (Aldi)', 6.00, 3.0, 630, genericName: 'Cherries', storeId: _storeAldi),
    _i('Cherries (Waitrose)', 8.50, 1.0, 630, genericName: 'Cherries', storeId: _storeWaitrose),
    _i('Cherries (Tesco)', 7.00, 2.5, 630, genericName: 'Cherries', storeId: _storeTesco),
    _i('Cherries (Asda)', 6.50, 1.5, 630, genericName: 'Cherries', storeId: _storeAsda),
  ],
};

final List<Recipe> mockRecipes = [
  Recipe(
    id: 'r-1',
    name: 'Scrambled Eggs on Toast',
    requiredIngredients: ['Eggs', 'Milk', 'Flour'],
    prepTimeMinutes: 10,
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    calories: 420,
    macros: Macros(proteinG: 22.0, carbsG: 38.0, fatG: 18.0),
    nutrients: {'Iron (mg)': 3.2, 'Calcium (mg)': 180.0, 'Vitamin D (µg)': 2.5},
  ),
  Recipe(
    id: 'r-2',
    name: 'Tomato & Cucumber Salad',
    requiredIngredients: ['Tomatoes', 'Cucumber', 'Lettuce'],
    prepTimeMinutes: 5,
    allergens: [],
    calories: 85,
    macros: Macros(proteinG: 3.0, carbsG: 14.0, fatG: 1.5),
    nutrients: {
      'Vitamin C (mg)': 28.0,
      'Potassium (mg)': 410.0,
      'Fibre (g)': 3.1,
    },
  ),
  Recipe(
    id: 'r-3',
    name: 'Simple Pasta',
    requiredIngredients: ['Pasta', 'Tomatoes', 'Milk'],
    prepTimeMinutes: 20,
    allergens: ['Gluten', 'Dairy'],
    calories: 510,
    macros: Macros(proteinG: 16.0, carbsG: 72.0, fatG: 12.0),
    nutrients: {
      'Iron (mg)': 2.1,
      'Calcium (mg)': 120.0,
      'Vitamin C (mg)': 14.0,
    },
  ),
];

final List<Store> mockStores = [
  Store(
    id: 's-aldi',
    name: 'Aldi',
    postcode: 'PO4 8SL',
    latitude: 50.7972378,
    longitude: -1.0687938,
  ),
  Store(
    id: 's-waitrose',
    name: 'Waitrose',
    postcode: 'PO1 3HZ',
    latitude: 50.792,
    longitude: -1.0905,
  ),
  Store(
    id: 's-tesco',
    name: 'Tesco',
    postcode: 'PO1 1RS',
    latitude: 50.8008788,
    longitude: -1.0874245,
  ),
  Store(
    id: 's-asda',
    name: 'Asda',
    postcode: 'PO3 5NP',
    latitude: 50.829,
    longitude: -1.054,
  ),
];
